package model

import "time"

// FileDiff represents a parsed diff for a single file.
type FileDiff struct {
	OldName string
	NewName string
	Hunks   []Hunk
}

// Hunk represents a contiguous block of changes within a file diff.
type Hunk struct {
	OldStartLine int
	OldLineCount int
	NewStartLine int
	NewLineCount int
	Content      string
}

// ChangedFunc represents a function whose body overlaps with a diff hunk.
type ChangedFunc struct {
	FilePath    string
	Package     string
	Name        string
	Signature   string
	Body        string
	StartLine   int
	EndLine     int
	Imports     []string
	TypeDefs    []string
	DiffContext string // the relevant diff hunks for this function
}

// Mutant represents a single mutation generated by the LLM.
type Mutant struct {
	ID          string `json:"id"`
	FuncName    string `json:"func_name"`
	Description string `json:"description"`
	Original    string `json:"original"`
	Mutated     string `json:"mutated"`
}

// GeneratedTest represents a test generated by the LLM.
type GeneratedTest struct {
	ID       string `json:"id"`
	MutantID string `json:"mutant_id"`
	FuncName string `json:"func_name"`
	TestName string `json:"test_name"`
	TestCode string `json:"test_code"`
}

// LLMResponse represents the parsed response from the LLM.
type LLMResponse struct {
	Mutants []Mutant        `json:"mutants"`
	Tests   []GeneratedTest `json:"tests"`
}

// TestResult represents the outcome of running a generated test.
type TestResult struct {
	Test           GeneratedTest
	Mutant         Mutant
	PassOriginal   bool
	FailMutant     bool
	IsCatching     bool
	OriginalOutput string
	MutantOutput   string
	Confidence     float64
	FilteredReason string
}

// PipelineResult holds the overall result of a pipeline run.
type PipelineResult struct {
	FilesAnalyzed    int
	FuncsAnalyzed    int
	MutantsGenerated int
	TestsGenerated   int
	TestsRun         int
	CatchingTests    int
	FilteredTests    int
	Results          []TestResult
	Duration         time.Duration
}
