package model

import "time"

// FileDiff represents a parsed diff for a single file.
type FileDiff struct {
	OldName      string
	NewName      string
	Hunks        []Hunk
	ParentSource []byte // full file content at parent revision
}

// Hunk represents a contiguous block of changes within a file diff.
type Hunk struct {
	OldStartLine int
	OldLineCount int
	NewStartLine int
	NewLineCount int
	Content      string
}

// ChangedFunc represents a function whose body overlaps with a diff hunk.
type ChangedFunc struct {
	FilePath        string
	Package         string
	Name            string
	Signature       string
	Body            string
	StartLine       int
	EndLine         int
	Imports         []string
	TypeDefs        []string
	DiffContext     string // the relevant diff hunks for this function
	ParentSignature string // function signature in parent revision
	ParentBody      string // function body in parent revision
}

// Risk represents a potential bug risk identified by the LLM.
type Risk struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

// Mutant represents a single mutation generated by the LLM.
type Mutant struct {
	ID          string `json:"id"`
	FuncName    string `json:"func_name"`
	Description string `json:"description"`
	Original    string `json:"original"`
	Mutated     string `json:"mutated"`
	RiskID      string `json:"risk_id"`
}

// GeneratedTest represents a test generated by the LLM.
type GeneratedTest struct {
	ID       string `json:"id"`
	MutantID string `json:"mutant_id"`
	FuncName string `json:"func_name"`
	TestName string `json:"test_name"`
	TestCode string `json:"test_code"`
}

// CatchingLLMResponse represents the parsed response from the intent-aware LLM.
type CatchingLLMResponse struct {
	Intent  string          `json:"intent"`
	Risks   []Risk          `json:"risks"`
	Mutants []Mutant        `json:"mutants"`
	Tests   []GeneratedTest `json:"tests"`
}

// TestResult represents the outcome of running a generated test.
type TestResult struct {
	Test           GeneratedTest
	Mutant         Mutant
	PassParent     bool    // test passes on old/parent code
	FailDiff       bool    // test fails on new/diff code
	IsCatching     bool    // PassParent && FailDiff
	ParentOutput   string  // output from running on parent code
	DiffOutput     string  // output from running on new/diff code
	BehaviorChange string  // human-readable description of what changed
	Assessment     float64 // true/false positive score (-1 to 1)
	Confidence     float64 // kept for backward compat
	FilteredReason string
}

// CatchSummary aggregates test results for a single risk/mutant pair.
type CatchSummary struct {
	Risk           Risk
	Mutant         Mutant
	Tests          []TestResult
	IsWeakCatch    bool
	Assessment     float64 // aggregated -1 to 1
	BehaviorChange string
}

// PipelineResult holds the overall result of a pipeline run.
type PipelineResult struct {
	FilesAnalyzed    int
	FuncsAnalyzed    int
	RisksIdentified  int
	MutantsGenerated int
	TestsGenerated   int
	TestsRun         int
	WeakCatches      int
	StrongCatches    int
	FilteredTests    int
	Results          []TestResult
	Duration         time.Duration
	Intent           string // aggregated intent from all functions
}
