package model

import "time"

// FileDiff represents a parsed diff for a single file.
type FileDiff struct {
	OldName      string
	NewName      string
	Hunks        []Hunk
	ParentSource []byte // full file content at parent revision
}

// Hunk represents a contiguous block of changes within a file diff.
type Hunk struct {
	OldStartLine int
	OldLineCount int
	NewStartLine int
	NewLineCount int
	Content      string
}

// ChangedFunc represents a function whose body overlaps with a diff hunk.
type ChangedFunc struct {
	FilePath        string
	Package         string
	Name            string
	Signature       string
	Body            string
	StartLine       int
	EndLine         int
	Imports         []string
	TypeDefs        []string
	DiffContext     string // the relevant diff hunks for this function
	ParentSignature string // function signature in parent revision
	ParentBody      string // function body in parent revision
}

// Risk represents a potential bug risk identified by the LLM.
type Risk struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

// Mutant represents a single mutation generated by the LLM.
type Mutant struct {
	ID          string `json:"id"`
	FuncName    string `json:"func_name"`
	Description string `json:"description"`
	Original    string `json:"original"`
	Mutated     string `json:"mutated"`
	RiskID      string `json:"risk_id"`
}

// GeneratedTest represents a test generated by the LLM.
type GeneratedTest struct {
	ID       string `json:"id"`
	MutantID string `json:"mutant_id"`
	FuncName string `json:"func_name"`
	TestName string `json:"test_name"`
	TestCode string `json:"test_code"`
}

// CatchingLLMResponse represents the parsed response from the intent-aware LLM.
type CatchingLLMResponse struct {
	Intent  string          `json:"intent"`
	Risks   []Risk          `json:"risks"`
	Mutants []Mutant        `json:"mutants"`
	Tests   []GeneratedTest `json:"tests"`
}

// TestResult represents the outcome of running a generated test.
type TestResult struct {
	Test           GeneratedTest `json:"test"`
	Mutant         Mutant        `json:"mutant"`
	PassParent     bool          `json:"pass_parent"`
	FailDiff       bool          `json:"fail_diff"`
	IsCatching     bool          `json:"is_catching"`
	ParentOutput   string        `json:"parent_output,omitempty"`
	DiffOutput     string        `json:"diff_output,omitempty"`
	BehaviorChange string        `json:"behavior_change,omitempty"`
	Question       string        `json:"question,omitempty"`
	Assessment     float64       `json:"assessment"`
	Confidence     float64       `json:"confidence"`
	FilteredReason string        `json:"filtered_reason,omitempty"`
}

// CatchSummary aggregates test results for a single risk/mutant pair.
type CatchSummary struct {
	Risk           Risk
	Mutant         Mutant
	Tests          []TestResult
	IsWeakCatch    bool
	Assessment     float64 // aggregated -1 to 1
	BehaviorChange string
	Question       string // "Is it expected that..." question for the developer
}

// PipelineResult holds the overall result of a pipeline run.
type PipelineResult struct {
	FilesAnalyzed    int           `json:"files_analyzed"`
	FuncsAnalyzed    int           `json:"funcs_analyzed"`
	RisksIdentified  int           `json:"risks_identified"`
	MutantsGenerated int           `json:"mutants_generated"`
	TestsGenerated   int           `json:"tests_generated"`
	TestsRun         int           `json:"tests_run"`
	WeakCatches      int           `json:"weak_catches"`
	StrongCatches    int           `json:"strong_catches"`
	FilteredTests    int           `json:"filtered_tests"`
	Results          []TestResult  `json:"results"`
	Duration         time.Duration `json:"duration"`
	Intent           string        `json:"intent,omitempty"`
}
